export declare const rdfTypePredicateURL = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";
export declare const rdfTypePredicate: import("rdf-data-factory").NamedNode<"http://www.w3.org/1999/02/22-rdf-syntax-ns#type">;
export declare const shaclNodeShapeUrl = "http://www.w3.org/ns/shacl#NodeShape";
export declare const shaclNodeShape: import("rdf-data-factory").NamedNode<"http://www.w3.org/ns/shacl#NodeShape">;
export declare const shaclTargetNodeUrl = "http://www.w3.org/ns/shacl#targetNode";
export declare const shaclTargetNode: import("rdf-data-factory").NamedNode<"http://www.w3.org/ns/shacl#targetNode">;
export declare const typeCanonicalCollectionURL = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#canonical-collection";
export declare const typeCanonicalCollection: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#canonical-collection">;
export declare const predicateOneFileOneResourceURL = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#one-file-one-resource";
export declare const predicateOneFileOneResource: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#one-file-one-resource">;
export declare const updateConditionPredicateURL = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#update-condition";
export declare const updateConditionPredicate: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#update-condition">;
export declare const typeUpdateConditionPreferStaticURL = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#update-prefer-static";
export declare const typeUpdateConditionPreferStatic: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#update-prefer-static">;
export declare const saveConditionPredicateURL = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#save-condition";
export declare const saveConditionPredicate: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#save-condition">;
export declare const typeSaveConditionAlwaysStoreURL = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#always-stored";
export declare const typeSaveConditionAlwaysStore: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#always-stored">;
export declare const resourceDescriptionPredicateURL = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#resource-description";
export declare const resourceDescriptionPredicate: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#resource-description">;
export declare const typeResourceDescriptionShaclURL = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#shacl-descriptor";
export declare const typeResourceDescriptionShacl: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#shacl-descriptor">;
export declare const shaclShapeLinkUrl = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#shacl-shape";
export declare const shaclShapeLink: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#shacl-shape">;
export declare const groupStrategyPredicateURL = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#group-strategy";
export declare const groupStrategyPredicate: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#group-strategy">;
export declare const typeGroupStrategyUriTemplateURL = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#group-strategty-uri-template";
export declare const typeGroupStrategyUriTemplate: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#group-strategty-uri-template">;
export declare const groupStrategyUriTemplateUrl = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#uri-template";
export declare const groupStrategyUriTemplate: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#uri-template">;
export declare const groupStrategyRegexMatchUrl = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#regex-match";
export declare const groupStrategyRegexMatch: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#regex-match">;
export declare const groupStrategyRegexReplaceUrl = "https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#regex-replace";
export declare const groupStrategyRegexReplace: import("rdf-data-factory").NamedNode<"https://thesis.jitsedesmet.be/solution/storage-guidance-vocabulary/#regex-replace">;
