prefix ns1: <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix card: <http://localhost:3000/pods/00000000000000000096/profile/card#>
prefix tag: <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/tag/>
prefix resource: <http://localhost:3000/dbpedia.org/resource/>
prefix res: <http://localhost:3000/pods/00000000000000000096/posts/2024-05-08#>

DELETE DATA {
    res:416608218494388
        a ns1:Post ;
        ns1:browserUsed "Chrome" ;
        ns1:content
            "I want to eat an apple." ;
        ns1:creationDate
            "2024-05-08T23:23:56.83Z"^^xsd:dateTime ;
        ns1:id "416608218494388"^^xsd:long ;
        ns1:hasCreator card:me ;
        ns1:hasTag tag:Alanis_Morissette, tag:Austria ;
        ns1:isLocatedIn resource:China ;
        ns1:locationIP "1.83.28.23" .
}
