prefix ns1: <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/vocabulary/>
prefix tag: <http://localhost:3000/www.ldbc.eu/ldbc_socialnet/1.0/tag/>

INSERT {
    ?id ns1:hasTag tag:Cheese
} where {
    ?id ns1:hasTag tag:Austria
}
